import Footer from "@/components/Footer"
import Nav from "@/components/Nav"
import "@/styles/globals.css";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function RootLayout({ children }) {
 return (
  <html lang="en">
  <body>
    <Nav />
    <div className="main"></div>
    <main className="app bg-meta-2">{children}
    <Footer />
    </main>
  </body>
</html>
  )
}
